config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
    resources :admins
    resources :subjects
    resources :questions
  end
  devise_for :admins
  devise_for :users
  root to: 'site/welcome#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, allow_destroy: true, reject_if: :all_blank
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice/admin_controller.rb
class AdminsBackoffice::AdminController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:edit, :update]
  
  def index
    @admins = Admin.all
  end
  
  def edit
  end

  def update
    if @admin.update(admin_params)
      redirect_to admins_backoffice_admin_index_path, notice: "Administrador atualizado com sucesso"
    else
      render :edit
    end
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def verify_password
    if params[:admin][:password].blank? &&  params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end

  def admin_params
    params.require(:admin).permit(:email,:password,:password_confirmation)
  end
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:edit, :update,:destroy]
  
  def index
    @admins = Admin.order(:email).page(params[:page]).per(20)
  end
 
  def new
    @admin = Admin.new
  end
 
  def edit
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: "Administrador registrado com sucesso"
    else
      render :new
    end
  end

  def update
    if @admin.update(admin_params)
      redirect_to admins_backoffice_admins_path, notice: "Administrador atualizado com sucesso"
    else
      render :edit
    end
  end

  def destroy
    begin
      @admin.destroy!
      redirect_to admins_backoffice_admins_path, notice: "Administrador excluído com sucesso"
    rescue
      redirect_to admins_backoffice_admins_path, notice: "Não foi possível excluir"
    end
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def verify_password
    if params[:admin][:password].blank? &&  params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end

  def admin_params
    params.require(:admin).permit(:email,:password,:password_confirmation)
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: [:edit, :update,:destroy]
  
  def index
    @questions = Question.includes(:subject).order('id desc').page(params[:page]).per(20)
  end
 
  def new
    @question = Question.new
    @subjects = Subject.order(:description)
  end
 
  def edit
    @subjects = Subject.order(:description)
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to admins_backoffice_questions_path, notice: "Questão registrada com sucesso"
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admins_backoffice_questions_path, notice: "Questão atualizada com sucesso"
    else
      render :edit
    end
  end

  def destroy
    begin
      @question.destroy!
      redirect_to admins_backoffice_questions_path, notice: "Questão excluída com sucesso"
    rescue
      redirect_to admins_backoffice_questions_path, notice: "Não foi possível excluir"
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:description,:subject_id, answers_attributes: [:id, :description, :correct, :_destroy])
  end
end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :set_subject, only: [:edit, :update,:destroy]
  
  def index
    @subjects = Subject.order(:description).page(params[:page]).per(20)
  end
 
  def new
    @subject = Subject.new
  end
 
  def edit
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      redirect_to admins_backoffice_subjects_path, notice: "Assunto registrado com sucesso"
    else
      render :new
    end
  end

  def update
    if @subject.update(subject_params)
      redirect_to admins_backoffice_subjects_path, notice: "Assunto atualizado com sucesso"
    else
      render :edit
    end
  end

  def destroy
    begin
      @subject.destroy!
      redirect_to admins_backoffice_subjects_path, notice: "Assunto excluído com sucesso"
    rescue
      redirect_to admins_backoffice_subjects_path, notice: "Não foi possível excluir"
    end
  end

  private

  def set_subject
    @subject = Subject.find(params[:id])
  end

  def subject_params
    params.require(:subject).permit(:description)
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController 
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  layout 'admins_backoffice'
  before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  def index
  end
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  layout 'users_backoffice'
  before_action :authenticate_user!
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def botao_salvar
    ('<div class="pull-right"><button type="submit" class="btn btn-primary"><span class="fa fa-save"></span> '+t('messages.save') +'</button></div>').html_safe
  end

  def botao_voltar(link)
    link_to('<i class="fa fa-arrow-left"></i> '.html_safe + t('messages.back'), link, class: "btn btn-xs btn-default")
  end
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins_backoffice/admin/edit.html.erb
<h1 class="page-header">Editar Administrador </h1>
<%= link_to '<i class="fa fa-arrow-left"></i> Voltar'.html_safe, admins_backoffice_admin_index_path, class: "btn btn-xs btn-default" %>
<hr>
<% if @admin.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
    <ul>
      <% @admin.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="panel panel-default">
  <div class="panel-heading">Editando o administrador #<%= @admin.id %> </div>
  <div class="panel-body">
    <%= form_with(model: [ :admins_backoffice, @admin ], local: true) do |form| %>
      <div class="row">
        <div class="col-md-12 form-group">
          <%= form.label :email %>
          <%= form.text_field :email, class:'form-control' %>
        </div>
        <div class="col-md-6 form-group">
          <%= form.label :password %>
          <%= form.password_field :password, class:'form-control' %>
        </div>
        <div class="col-md-6 form-group">
          <%= form.label :password_confirmation %>
          <%= form.password_field :password_confirmation, class:'form-control' %>
        </div>
      </div>
      <div class="pull-right">
        <button type="submit" class="btn btn-primary"><span class="fa fa-save"></span> Salvar</button>
      </div>
    <% end %>
  </div>
</div>

app/views/admins_backoffice/admin/index.html.erb
<h1 class="page-header">Administradores</h1>
<div class="table-responsible">
  <table class="table table-striped table-bordered table-hover">
    <tr>
      <th>#</th>
      <th>Email</th>
      <th>Ações</th>
    </tr>
    <% @admins.each do |admin| %>
      <tr>
        <td class="small_col"><%= admin.id %></td>
        <td><%= admin.email %></td>
        <td class="small_col">
          <%= link_to '<span class="fa fa-edit"></span>'.html_safe, edit_admins_backoffice_admin_path(admin.id) , class:"btn btn-primary btn-circle" %>
          <a type="button" class="btn btn-danger btn-circle"><span class="fa fa-times"></span></a>          
        </td>
      <tr>
    <% end %>
  </table>
</div>

<style>
  .small_col{
    width: 10%;
  }
</style>

app/views/admins_backoffice/admins/_form.html.haml
=botao_voltar(admins_backoffice_admins_path)
%hr
  - if @admin.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{:type=>"button", :data-dismiss=>"alert", :aria-hidden=>"true" }x
      %ul
        - @admin.errors.full_messages.each do |msg|
          %li= msg

.panel.panel-default
  .panel-heading=#{@admin.model_name.human @admin.id}
  .panel-body
    = form_with(model: [ :admins_backoffice, @admin ], local: true) do |form|
      .row
        .col-md-12.form-group
          = form.label(:email)
          = form.text_field(:email, class:'form-control')
        .col-md-6.form-group
          = form.label(:password)
          = form.text_field(:password, class:'form-control')
        .col-md-6.form-group
          = form.label(:password_confirmation)
          = form.text_field(:password_confirmation, class:'form-control')
      =botao_salvar()

app/views/admins_backoffice/admins/edit.html.haml
%h2.page-header=t('messages.edit', model: @admin.model_name.human )
= render 'form'

app/views/admins_backoffice/admins/index.html.haml
%h2.page-header=t('messages.listing', model: @admins.model_name.human(count: 2) )
%div.table-responsible
  %table.table.table-striped.table-bordered.table-hover
    %tr
      %th= @admins.model.human_attribute_name(:id)
      %th= @admins.model.human_attribute_name(:email)
      %th= link_to('<span class="fa fa-plus"></span>'.html_safe, new_admins_backoffice_admin_path , class:"btn btn-success btn-circle")
    -@admins.each do |admin|
      %tr
        %td.small_col= admin.id
        %td= admin.email
        %td.small_col
          = link_to('<span class="fa fa-edit"></span>'.html_safe, edit_admins_backoffice_admin_path(admin) , class:"btn btn-primary btn-circle")
          = link_to('<span class="fa fa-times"></span>'.html_safe, admins_backoffice_admin_path(admin) , class:"btn btn-danger btn-circle",method:'delete', data: {confirm: "Deseja realmente excluir este registro?"})
  = paginate(@admins)

%style .small_col{width: 10%;}

app/views/admins_backoffice/admins/new.html.haml
%h2.page-header=t('messages.new', model: @admin.model_name.human )
= render 'form'

app/views/admins_backoffice/questions/_answer_fields.html.haml
.nested-fields
  .row
    .col-md-10.form-group
      = f.text_field(:description, class:'form-control')
    .col-md-1.form-group
      = f.check_box(:correct, class:'form-control')
    .col-md-1.form-group
      =link_to_remove_association("<span class='fa fa-times'></span>".html_safe, f, class: 'btn btn-block btn-default')

app/views/admins_backoffice/questions/_form.html.haml
=botao_voltar(admins_backoffice_questions_path)
%hr
  - if @question.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{:type=>"button", :data-dismiss=>"alert", :aria-hidden=>"true" }x
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

.panel.panel-default
  .panel-heading=@question.model_name.human + ' ' + @question.id.to_s
  .panel-body
    = form_with(model: [ :admins_backoffice, @question ], local: true) do |form|
      .row
        .col-md-12.form-group
          = form.label(:subject)
          = form.collection_select(:subject_id,@subjects,:id,:description,{}, {class:'form-control'})
        .col-md-12.form-group
          = form.label(:description)
          = form.text_area(:description, class:'form-control', rows: 5)
      %h3=Answer.model_name.human
      #awnsers
        .row
          .col-md-10.form-group
            = form.label(:description)
          .col-md-1.form-group
            = form.label('Correta?')
          .col-md-1.form-group
            = form.label(' ')
        = form.fields_for(:answers) do |answer|
          = render('answer_fields', f: answer)
        .links
          = link_to_add_association('<span class="fa fa-plus"></span> Adicionar Resposta'.html_safe, form, :answers, class:"btn btn-default")
      =botao_salvar()

app/views/admins_backoffice/questions/edit.html.haml
%h2.page-header=t('messages.edit', model: @question.model_name.human )
= render 'form'

app/views/admins_backoffice/questions/index.html.haml
%h2.page-header=t('messages.listing', model: @questions.model_name.human(count: 2) )
%div.table-responsible
  %table.table.table-striped.table-bordered.table-hover
    %tr
      %th= @questions.model.human_attribute_name(:id)
      %th= @questions.model.human_attribute_name(:description)
      %th= @questions.model.human_attribute_name(:subject)
      %th= link_to('<span class="fa fa-plus"></span>'.html_safe, new_admins_backoffice_question_path , class:"btn btn-success btn-circle")
    -@questions.each do |question|
      %tr
        %td.small_col= question.id
        %td= question.description.truncate(80)
        %td= question.subject.description
        %td.small_col
          = link_to('<span class="fa fa-edit"></span>'.html_safe, edit_admins_backoffice_question_path(question) , class:"btn btn-primary btn-circle")
          = link_to('<span class="fa fa-times"></span>'.html_safe, admins_backoffice_question_path(question) , class:"btn btn-danger btn-circle",method:'delete', data: {confirm: "Deseja realmente excluir este registro?"})
  = paginate(@questions)

%style .small_col{width: 10%;}

app/views/admins_backoffice/questions/new.html.haml
%h2.page-header=t('messages.new', model: @question.model_name.human )
= render 'form'

app/views/admins_backoffice/subjects/_form.html.haml
=botao_voltar(admins_backoffice_subjects_path)
%hr
  - if @subject.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{:type=>"button", :data-dismiss=>"alert", :aria-hidden=>"true" }x
      %ul
        - @subject.errors.full_messages.each do |msg|
          %li= msg

.panel.panel-default
  .panel-heading=@subject.model_name.human + ' ' + @subject.id.to_s
  .panel-body
    = form_with(model: [ :admins_backoffice, @subject ], local: true) do |form|
      .row
        .col-md-12.form-group
          = form.label(:description)
          = form.text_field(:description, class:'form-control')
      =botao_salvar()

app/views/admins_backoffice/subjects/edit.html.haml
%h2.page-headerr=t('messages.edit', model: @subject.model_name.human )
= render 'form'

app/views/admins_backoffice/subjects/index.html.haml
%h2.page-header=t('messages.listing', model: @subjects.model_name.human(count: 2) )
%div.table-responsible
  %table.table.table-striped.table-bordered.table-hover
    %tr
      %th= @subjects.model.human_attribute_name(:id)
      %th= @subjects.model.human_attribute_name(:description)
      %th= link_to('<span class="fa fa-plus"></span>'.html_safe, new_admins_backoffice_subject_path , class:"btn btn-success btn-circle")
    -@subjects.each do |subject|
      %tr
        %td.small_col= subject.id
        %td= subject.description
        %td.small_col
          = link_to('<span class="fa fa-edit"></span>'.html_safe, edit_admins_backoffice_subject_path(subject) , class:"btn btn-primary btn-circle")
          = link_to('<span class="fa fa-times"></span>'.html_safe, admins_backoffice_subject_path(subject) , class:"btn btn-danger btn-circle",method:'delete', data: {confirm: "Deseja realmente excluir este registro?"})
  = paginate(@subjects)

%style .small_col{width: 10%;}

app/views/admins_backoffice/subjects/new.html.haml
%h2.page-headerr=t('messages.new', model: @subject.model_name.human )
= render 'form'

app/views/admins_backoffice/welcome/index.html.haml
%h1.page-header Dashboard

app/views/site/welcome/index.html.erb
<h1>Site::Welcome#index</h1>
<p>Find me in app/views/site/welcome/index.html.erb</p>

<% if user_signed_in? %>
  <p>Usuário está logado - <%= current_user.email %></p>
<% else %>
  <p>Usuário não está logado</p>
<% end %>

<% if admin_signed_in? %>
  <p>Administrador está logado - <%= current_admin.email %></p>
<% else %>
  <p>Administrador não está logado</p>
<% end %>

<%= link_to 'Área do Admin', admins_backoffice_welcome_index_path %>
<%= link_to 'Área do Usuário', users_backoffice_welcome_index_path %>

app/views/users_backoffice/welcome/index.html.erb
<h1>UsersBackoffice::Welcome#index</h1>
<p>Find me in app/views/users_backoffice/welcome/index.html.erb</p>

<%= link_to 'Página Inicial', root_path %>