config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
    resources :admins
    resources :subjects
    resources :questions
  end
  devise_for :admins
  devise_for :users
  root to: 'site/welcome#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, allow_destroy: true, reject_if: :all_blank
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  layout 'admins_backoffice'
  before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  layout 'users_backoffice'
  before_action :authenticate_user!
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def botao_salvar
    ('<div class="pull-right"><button type="submit" class="btn btn-primary"><span class="fa fa-save"></span> '+t('messages.save') +'</button></div>').html_safe
  end

  def botao_voltar(link)
    link_to('<i class="fa fa-arrow-left"></i> '.html_safe + t('messages.back'), link, class: "btn btn-xs btn-default")
  end
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/layouts/admins_backoffice.html.haml
<!DOCTYPE html>
%html
  %head
    %meta{ :charset => "utf-8"}
    %meta{ :http-equiv => "X-UA-Compatible", :content => "IE=edge"}
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1"}
    %meta{ :name => "description", :content => ""}
    %meta{ :name => "author", :content => ""}

    %title TimeToAnswer

    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application'
    = stylesheet_link_tag 'admins_backoffice'

  %body
    #wrapper
      %nav.navbar.navbar-default.navbar-static-top{ role:"navigation", style:"margin-bottom: 0"}
        .navbar-header
          %button{:type => "button", :class => "navbar-toggle", :data-toggle => "collapse", :data-target => ".navbar-collapse"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href:"index.html"} Painel Administrador
        %ul.nav.navbar-top-links.navbar-right
          %li.dropdown
            %a.dropdown-toggle{ :data-toggle => "dropdown", :href =>"#"}
              %i.fa.fa-user.fa-fw
              %i.fa.fa-caret-down
            %ul.dropdown-menu.dropdown-user
              %li= link_to('<i class="fa fa-sign-out fa-fw"></i> Logout'.html_safe, destroy_admin_session_path, method: :delete)
        .navbar-default.sidebar{role:"navigation"}
          .sidebar-nav.navbar-collapse
            %ul.nav#side-menu
              %li= link_to('<i class="fa fa-home fa-fw"></i> Ínicio'.html_safe, root_path)
              %li= link_to('<i class="fa fa-dashboard fa-fw"></i> Dashboard'.html_safe, admins_backoffice_welcome_index_path)
              %li= link_to('<i class="fa fa-users fa-fw"></i> Administradores'.html_safe, admins_backoffice_admins_path)
              %li= link_to('<i class="fa fa-file-text-o fa-fw"></i> Assuntos'.html_safe, admins_backoffice_subjects_path)
              %li= link_to('<i class="fa fa-th-list fa-fw"></i> Questões'.html_safe, admins_backoffice_questions_path)
      
      #page-wrapper
        .container-fluid
          .row
            .col-lg-12            
              = yield            

    = javascript_include_tag 'application'
    = javascript_include_tag 'admins_backoffice'

    - if notice.present?
      %script
        :plain
          $.bootstrapGrowl("#{notice}",{
            type: 'success', //null,info,danger,success
            align: 'right',
            allow_dismiss: true,
            stackup_spacing: 10
          });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/profiles_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Área do Usuário</h1>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1>Layout site</h1>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/users_backoffice.html.haml
<!DOCTYPE html>
%html
  %head
    %meta{:http-equiv=>"Content-Type", :content=>"text/html; charset=UTF-8"}
    %meta{:charset=>"utf-8"}
    %meta{:http-equiv=>"X-UA-Compatible", :content=>"IE=edge"}
    %meta{:name=>"viewport", :content=>"width=device-width, initial-scale=1"}
    = csrf_meta_tags
    = csp_meta_tag
    
    %title TimeToAnswer
    
    = stylesheet_link_tag('application')
    = stylesheet_link_tag('users_backoffice')

  %body.nav-md
    .container.body
      .main_container
        .col-md-3.left_col.menu_fixed
          .left_col.scroll-view
            .navbar.nav_title{:style=>"border: 0;"}
              %a.site_title{:href=>"index.html"} 
                %i.fa.fa-paw
                %span Gentelella Alela!
            .clearfix
            .profile.clearfix
              .profile_pic
                = image_tag('img.jpg', alt:"...", class:"img-circle profile_img")
              .profile_info
                %span Welcome,
                %h2 John Doe
            %br
            #sidebar-menu.main_menu_side.hidden-print.main_menu
              .menu_section
                %h3 General
                %ul.nav.side-menu
                  %li
                    %a
                      %i.fa.fa-home Home 
                      %span.fa.fa-chevron-down
                    %ul.nav.child_menu
                      %li
                        %a{:href=>"index.html"} Dashboard
                        %a{:href=>"index2.html"} Dashboard2
                        %a{:href=>"index3.html"} Dashboard3
                  %li
                    %a
                      %i.fa.fa-edit Forms 
                      %span.fa.fa-chevron-down
                    %ul.nav.child_menu
                      %li
                        %a{:href=>"form.html"} General Form
                      %li
                        %a{:href=>"form_advanced.html"} Advanced Components
                      %li
                        %a{:href=>"form_validation.html"} Form Validation
                      %li
                        %a{:href=>"form_wizards.html"} Form Wizard
                      %li
                        %a{:href=>"form_upload.html"} Form Upload
                      %li
                        %a{:href=>"form_buttons.html"} Form Buttons
              
            .sidebar-footer.hidden-small
              = link_to('<span class="glyphicon glyphicon-off" aria-hidden="true"></span>'.html_safe, destroy_user_session_path, method: :delete, 'data-toggle':"tooltip", 'data-placement':"top", 'title':"Logout")
              
        .top_nav
          .nav_menu
            %nav
              .nav.toggle
                %a#menu_toggle
                  %i.fa.fa-bars
              %ul.nav.navbar-nav.navbar-right
                %li
                  %a.user-profile.dropdown-toggle{:href=>"javascript:;" , 'data-toggle'=>"dropdown", 'aria-expanded'=>"false"}
                    = image_tag('img.jpg', alt:"")
                    John Doe
                    %span.fa.fa-angle-down
                  %ul.dropdown-menu.dropdown-usermenu.pull-right
                    %li= link_to('<i class="fa fa-sign-out pull-right"></i> Logout</a>'.html_safe, destroy_user_session_path, method: :delete )
                %li.dropdown{:role=>"presentation"}
                  %a.dropdown-toggle.info-number{:href=>"javascript:;" , 'data-toggle'=>"dropdown", 'aria-expanded'=>"false"}
                    %i.fa.fa-envelope-o
                    %span.badge.bg-green 6
                  %ul#menu1.dropdown-menu.list-unstyled.msg_list{:role=>"menu"}
                    %li
                      %a
                        %span.image= image_tag('img.jpg', alt:"Profile Image")
                        %span
                          %span John Smith
                          %span.time 3 mins ago
                        %span.message Film festivals used to be do-or-die moments for movie makers. They were where...
                    %li
                      .text-center
                        %a
                          %strong See All Alerts
                          %i.fa.fa-angle-right

        .right_col{:role=>"main"}
          %div
            .page-title
              .title_left
                %h3 Área do Usuário
                = yield
                
        %footer
          .pull-right Gentelella - Bootstrap Admin Template by Colorlib
          .clearfix
    
    = javascript_include_tag('application')
    = javascript_include_tag('users_backoffice')